# Generated by Django 4.0.5 on 2022-06-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabberapi', '0002_comment_country_post_user_delete_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_description',
            new_name='user_fname',
        ),
        migrations.AddField(
            model_name='user',
            name='user_lname',
            field=models.TextField(default='[Last]'),
            preserve_default=False,
        ),
    ]
