# Generated by Django 4.0.5 on 2022-07-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabberapi', '0004_picture_alter_user_email_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
